#Ativar esse import quando for desenvolver ou testar aplicacao locamente e comentar quando for fazer deploy
#spring.config.import=classpath:application-secret.properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracao global para mapeamento de Enums no PostgreSQL
spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=pgsql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
